import Head from 'next/head';
import LandingPage from '../components/LandingPage';
import SecondPage from '../components/SecongPage';

export default function Home() {
  return (
    <div>
      <Head>
        <title>WEDDING INVITE</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <LandingPage />
      <SecondPage />
    </div>
  );
}
